name: Build & Publish Release APK

on:
  push:
    branches:
      - main
    tags:
      - '*'  
  pull_request:
    branches:
      - main   
    
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Release APK
        uses: r0user/release-apk@V1.0
            
